# Use trusty environment for a up-to-date version of autotools
sudo: required
dist: trusty
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - CFLAGS=-fsanitize=address
  - CFLAGS=-fsanitize=undefined
matrix:
  exclude:
    # UBSan requires GCC >= 4.9
    - os: linux
      compiler: gcc
      env: CFLAGS=-fsanitize=undefined
    # UBSan requires LLVM >= 3.3
    - os: osx
      compiler: clang
      env: CFLAGS=-fsanitize=undefined
    # GCC is linked to Clang on macOS
    - os: osx
      compiler: gcc
script:
  - ./autogen.sh
  - ./configure || (cat config.log; exit 1)
  - make || exit 1
  - make distcheck || (find . -name test-suite.log | xargs -t cat; exit 1)
