# Use trusty environment for a up-to-date version of autotools
sudo: required
dist: trusty
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - ./autogen.sh
  - ./configure || (cat config.log; exit 1)
  - make || exit 1
  - make check || (cat test-suite.log; exit 1)
